



NUMPY

In [8]:
#create a list of 1,00,00,00 salaries ranging from 50,000 to 1,50,00
import random
salary_list = [random.randint(50000, 150000) for _ in range(1000000)]

In [9]:
import statistics

In [10]:
%%timeit
statistics.mean(salary_list)

177 ms ± 3.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [2]:
import numpy as np


In [13]:
%%timeit
np.mean(salary_list)

40.4 ms ± 213 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

In [17]:
arr.mean()

np.float64(3.0)

In [30]:
# Job titles
job_titles = np.array(['Data Analyst', 'Data Scientist', 'Data Engineer', 'Machine Learning Engineer'])

# Base salaries
base_salaries = np.array( [60000, 80000, 75000, 90000, np.nan] )

# Bonus rates
bonus_rates = np.array([.05, .1, .08, .12, np.nan])

In [31]:
total_salaries = base_salaries * (1 + bonus_rates)
total_salaries

array([ 63000.,  88000.,  81000., 100800.,     nan])

In [25]:
%%timeit
total_salaries.mean()

2.37 μs ± 8.73 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [24]:
%%timeit
np.mean(total_salaries)


2.92 μs ± 11.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
a = np.arange(0, 16).reshape(4, 4)

In [18]:
a
b = a * 2
b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [17]:
b.sum(axis = 0)

array([48, 56, 64, 72])